# SITE CONFIGURATION
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://gentoomc.github.io/" # the base hostname & protocol for your site

# THEME-SPECIFIC CONFIGURATION
theme:
  # Meta
  title: Miri's Blog
  avatar: avatar.png
  gravatar: # Email MD5 hash
  description: "A website with blog posts and pages" # used by search engines

  # Header and footer text
  header_text: >
     <p>I'm Miri Cho, a grad student at Georgia Tech. 
        I love working on analytics projects and learning to use different data science tools.
        Currently, I'm working on several machine learning projects using python and open source databases.
     </p>


  header_text_feature_image:
  footer_text: >
   Powered by <a href="http://jekyllrb.com">Jekyll</a> with <a href="https://rohanchandra.github.io/project/type/">Type Theme</a>

  # Icons
  rss: false
  email_address: "miricho09@gmail.com"
  behance:
  bitbucket:
  dribbble:
  facebook:
  flickr:
  github: "Gentoomc"
  google_plus:
  instagram:
  linkedin:  "https://www.linkedin.com/in/miricho"
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:  # Full URL
  steam:
  tumblr:
  wordpress:
  youtube:

  # Scripts
  google_analytics: "UA-67783125-1"
  disqus_shortname:
  katex: true # Enable if using math markup

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next: "Next"
  str_prev: "Prev"
  str_continue_reading: "Continue reading"

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"
  
  # Post navigation
  post_navigation: true

# PAGINATION
paginate: 5
paginate_path: "blog/page:num"

# BUILD SETTINGS
markdown: kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: :compressed
